# Generated by Django 5.2.13 on 2026-07-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
