# Generated by Django 5.2.13 on 2026-07-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_research_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
