# Generated by Django 5.2.13 on 2026-07-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_research_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='image_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='link',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
